from typing import List, Annotated, Dict, TypedDict

from langchain_core.messages import BaseMessage
from langgraph.graph import add_messages
from pydantic import BaseModel, Field


class RawArticle(BaseModel):
    """Represents a single scraped article."""
    id: int
    url: str
    content: str

class ExtractedPerspective(BaseModel):
    """Represents a single perspective found within an article."""
    perspective_summary: str = Field(description="A concise, neutral summary of a distinct viewpoint expressed in the article.")
    key_arguments: List[str] = Field(description="A list of the main claims, rationales, or evidence supporting this perspective, as described in the article.")

class ArticlePerspectives(BaseModel):
    """A collection of extracted perspectives for a single article."""
    source_article_id: int
    perspectives: List[ExtractedPerspective]

class ConsolidatedPerspective(BaseModel):
    """Represents a final, clustered perspective with aggregated arguments of all articles."""
    arguments: List[str]

class FinalPerspective(BaseModel):
    """
    The final, detailed analysis of a single perspective about the topic.
    This perspective is synthesized based on the aggregated arguments for the consolidated perspectives.
    """
    narrative: str
    core_arguments: List[str]
    common_assumptions: List[str]
    strengths: List[str]
    weaknesses: List[str]


class State(TypedDict):
    messages: Annotated[List[BaseMessage], add_messages]
    topic: str

    search_queries: List[str] # TODO: potentially remove, since search queries can be generated by search agent
    raw_articles: List[RawArticle]
    extracted_perspectives: ArticlePerspectives
    consolidated_perspectives: Dict[str, ConsolidatedPerspective]

    identified_perspectives: Dict[str, FinalPerspective]
    summary: str

    iteration: int
    missing_perspectives: List[dict] # TODO: remove or change to List[str]
